import { sql } from 'kysely';
import { db, DIALECT } from './index';

/**
 * Migrations run automatically on boot (see hooks.server.ts), so a fresh
 * `docker run` creates its own schema with no manual step. Each migration is
 * idempotent and recorded in _migrations so it only runs once.
 *
 * Written in raw SQL that's valid on both SQLite and Postgres. The handful of
 * dialect differences (auto-increment PK, blob type, timestamp default) are
 * abstracted by the fragments below. Timestamps are stored as TEXT in the same
 * 'YYYY-MM-DD HH:MM:SS' UTC format on both engines, so all app-side date
 * parsing is identical regardless of dialect.
 */
const PG = DIALECT === 'postgres';

/** Auto-incrementing integer primary key. */
const PK = sql.raw(
  PG ? 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' : 'INTEGER PRIMARY KEY AUTOINCREMENT'
);
/** A TEXT timestamp column defaulting to "now" in UTC, same format on both. */
const TS_DEFAULT = sql.raw(
  PG
    ? "TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')"
    : "TEXT NOT NULL DEFAULT (datetime('now'))"
);
/** Binary blob type. */
const BLOB = sql.raw(PG ? 'BYTEA' : 'BLOB');

interface Migration {
  name: string;
  up: () => Promise<void>;
}

const migrations: Migration[] = [
  {
    name: '0001_initial',
    up: async () => {
      await sql`
        CREATE TABLE IF NOT EXISTS users (
          id            ${PK},
          username      TEXT NOT NULL UNIQUE,
          email         TEXT UNIQUE,
          password_hash TEXT,
          is_admin      INTEGER NOT NULL DEFAULT 0,
          created_at    ${TS_DEFAULT}
        )
      `.execute(db);

      await sql`
        CREATE TABLE IF NOT EXISTS branches (
          id         ${PK},
          user_id    INTEGER NOT NULL REFERENCES users(id),
          parent_id  INTEGER REFERENCES branches(id),
          name       TEXT NOT NULL,
          position   INTEGER NOT NULL DEFAULT 0,
          icon       TEXT,
          colour     TEXT,
          is_deleted INTEGER NOT NULL DEFAULT 0,
          created_at ${TS_DEFAULT},
          updated_at ${TS_DEFAULT}
        )
      `.execute(db);

      await sql`
        CREATE TABLE IF NOT EXISTS bookmarks (
          id         ${PK},
          user_id    INTEGER NOT NULL REFERENCES users(id),
          branch_id  INTEGER NOT NULL REFERENCES branches(id),
          title      TEXT NOT NULL,
          url        TEXT NOT NULL,
          notes      TEXT,
          position   INTEGER NOT NULL DEFAULT 0,
          is_deleted INTEGER NOT NULL DEFAULT 0,
          created_at ${TS_DEFAULT},
          updated_at ${TS_DEFAULT}
        )
      `.execute(db);

      await sql`CREATE INDEX IF NOT EXISTS ix_branches_user_parent
                ON branches (user_id, parent_id, position)`.execute(db);
      await sql`CREATE INDEX IF NOT EXISTS ix_bookmarks_user_branch
                ON bookmarks (user_id, branch_id, position)`.execute(db);
    }
  },
  {
    name: '0002_sessions',
    up: async () => {
      // id = sha256(token) hex, so a DB leak never exposes a usable cookie.
      await sql`
        CREATE TABLE IF NOT EXISTS sessions (
          id         TEXT PRIMARY KEY,
          user_id    INTEGER NOT NULL REFERENCES users(id),
          expires_at TEXT NOT NULL,
          created_at ${TS_DEFAULT}
        )
      `.execute(db);
      await sql`CREATE INDEX IF NOT EXISTS ix_sessions_user ON sessions (user_id)`.execute(db);
    }
  },
  {
    name: '0003_deleted_at',
    up: async () => {
      // Timestamps for the trash view + auto-purge. Added now (not in 0001) so
      // existing databases get them via ALTER without a rebuild.
      await sql`ALTER TABLE bookmarks ADD COLUMN deleted_at TEXT`.execute(db);
      await sql`ALTER TABLE branches  ADD COLUMN deleted_at TEXT`.execute(db);
    }
  },
  {
    name: '0004_favicons',
    up: async () => {
      // Per-host favicon cache. data IS NULL means "we tried and found none".
      await sql`
        CREATE TABLE IF NOT EXISTS favicons (
          host         TEXT PRIMARY KEY,
          data         ${BLOB},
          content_type TEXT,
          ok           INTEGER NOT NULL DEFAULT 0,
          fetched_at   ${TS_DEFAULT}
        )
      `.execute(db);
    }
  },
  {
    name: '0005_favicon_manual',
    up: async () => {
      // A manually-uploaded icon; never overwritten by the auto-refetch.
      await sql`ALTER TABLE favicons ADD COLUMN is_manual INTEGER NOT NULL DEFAULT 0`.execute(db);
    }
  },
  {
    name: '0006_link_health',
    up: async () => {
      // Link-rot checker state. All NULL until a bookmark is first checked.
      await sql`ALTER TABLE bookmarks ADD COLUMN link_status TEXT`.execute(db);
      await sql`ALTER TABLE bookmarks ADD COLUMN link_code INTEGER`.execute(db);
      await sql`ALTER TABLE bookmarks ADD COLUMN link_detail TEXT`.execute(db);
      await sql`ALTER TABLE bookmarks ADD COLUMN link_checked_at TEXT`.execute(db);
      // Speeds up the "broken links" report + badge counts.
      await sql`CREATE INDEX IF NOT EXISTS ix_bookmarks_link_status
                ON bookmarks (user_id, link_status)`.execute(db);
    }
  },
  {
    name: '0007_link_ignore',
    up: async () => {
      // Per-bookmark opt-out: exempt a link from the link-rot checker (e.g. a
      // site only reachable from certain networks). 1 = never checked/flagged.
      await sql`ALTER TABLE bookmarks ADD COLUMN link_ignore INTEGER NOT NULL DEFAULT 0`.execute(db);
    }
  },
  {
    name: '0008_tags',
    up: async () => {
      // Cross-cutting labels, independent of the folder tree. `hue` (0..359) is
      // the tag's colour; NULL means "derive from the name".
      await sql`
        CREATE TABLE IF NOT EXISTS tags (
          id         ${PK},
          user_id    INTEGER NOT NULL REFERENCES users(id),
          name       TEXT NOT NULL,
          hue        INTEGER,
          created_at ${TS_DEFAULT},
          UNIQUE (user_id, name)
        )
      `.execute(db);
      await sql`
        CREATE TABLE IF NOT EXISTS bookmark_tags (
          bookmark_id INTEGER NOT NULL REFERENCES bookmarks(id),
          tag_id      INTEGER NOT NULL REFERENCES tags(id),
          PRIMARY KEY (bookmark_id, tag_id)
        )
      `.execute(db);
      await sql`CREATE INDEX IF NOT EXISTS ix_bookmark_tags_tag
                ON bookmark_tags (tag_id)`.execute(db);
    }
  },
  {
    name: '0009_invites',
    up: async () => {
      // One-time invite links generated by admins. Only the sha256 of the token
      // is stored, so a DB leak can't yield a usable invite (same as sessions).
      await sql`
        CREATE TABLE IF NOT EXISTS invites (
          id         ${PK},
          token_hash TEXT NOT NULL UNIQUE,
          created_by INTEGER NOT NULL REFERENCES users(id),
          email      TEXT,
          note       TEXT,
          is_admin   INTEGER NOT NULL DEFAULT 0,
          expires_at TEXT,
          used_at    TEXT,
          used_by    INTEGER REFERENCES users(id),
          created_at ${TS_DEFAULT}
        )
      `.execute(db);
    }
  },
  {
    name: '0010_api_tokens',
    up: async () => {
      // Personal access tokens for the browser extension / API ingest. Only the
      // sha256 of the token is stored; the raw token is shown once at creation.
      await sql`
        CREATE TABLE IF NOT EXISTS api_tokens (
          id           ${PK},
          user_id      INTEGER NOT NULL REFERENCES users(id),
          name         TEXT NOT NULL,
          token_hash   TEXT NOT NULL UNIQUE,
          created_at   ${TS_DEFAULT},
          last_used_at TEXT
        )
      `.execute(db);
    }
  },
  {
    name: '0011_user_settings',
    up: async () => {
      // Per-user personalization preferences, stored as a small JSON document so
      // new settings can be added without a migration each time.
      await sql`ALTER TABLE users ADD COLUMN settings TEXT NOT NULL DEFAULT '{}'`.execute(db);
    }
  },
  {
    name: '0012_backgrounds',
    up: async () => {
      // Per-user custom background image, shown behind the folder tree and
      // bookmarks. One row per user; the bytes are served from /background.
      await sql`
        CREATE TABLE IF NOT EXISTS backgrounds (
          user_id      INTEGER PRIMARY KEY REFERENCES users(id),
          data         ${BLOB},
          content_type TEXT NOT NULL,
          updated_at   ${TS_DEFAULT}
        )
      `.execute(db);
    }
  },
  {
    name: '0013_app_settings',
    up: async () => {
      // Instance-wide key/value store: admin-controlled module enablement,
      // cached exchange rates, and any future app-level configuration.
      await sql`
        CREATE TABLE IF NOT EXISTS app_settings (
          key        TEXT PRIMARY KEY,
          value      TEXT NOT NULL,
          updated_at ${TS_DEFAULT}
        )
      `.execute(db);
    }
  }
];

export async function runMigrations(): Promise<void> {
  await sql`
    CREATE TABLE IF NOT EXISTS _migrations (
      name       TEXT PRIMARY KEY,
      applied_at ${TS_DEFAULT}
    )
  `.execute(db);

  const applied = (await sql<{ name: string }>`SELECT name FROM _migrations`.execute(db)).rows;
  const done = new Set(applied.map((r) => r.name));

  for (const m of migrations) {
    if (done.has(m.name)) continue;
    await m.up();
    await sql`INSERT INTO _migrations (name) VALUES (${m.name})`.execute(db);
    console.log(`[migrate] applied ${m.name}`);
  }
}
